import { sidebarToggler } from './components/sidebar-toggler.js';
import { nav } from './components/nav.js';
import { create } from './components/create.js';
import { user } from './components/user.js';
import { search } from './components/search.js';
import { sort } from './components/sort.js';
import { input } from './components/input.js';
import { message } from './components/message.js';
import { enter } from './components/enter.js';
import { dropdown } from './components/dropdown.js';
import { copy } from './components/copy.js';
import { price } from './components/price.js';
import { pricing } from './components/pricing.js';
import { tabs } from './components/tabs.js';
import { range } from './components/range.js';
import { popup } from './components/popup.js';
import { bubble } from './components/bubble.js';
import { scrollable } from './components/scrollable.js';
import { youtubePreview } from './components/youtube-preview.js';
import { editNotes } from './components/edit-notes.js';

document.addEventListener('DOMContentLoaded', () => {
    sidebarToggler();
    nav();
    create();
    user();
    search();
    sort();
    input();
    message();
    enter();
    dropdown();
    copy();
    price();
    pricing();
    tabs();
    range();
    popup();
    bubble();
    scrollable();
    youtubePreview();
    editNotes();
});
